apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app: nginx-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-html
  template:
    metadata:
      labels:
        app: nginx-html
    spec:
      containers:
      - name: nginx-html
        image: localhost:5000/localhost/html
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  selector:
    app: nginx-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80